export const mockMovies = [
  {
    imageUrl: 'https://example.com/images/inception.jpg',
    releaseDate: '2010-07-16',
    name: 'A Origem',
    rate: 8.8,
    genres: ['Ação', 'Ficção Científica', 'Thriller'],
    price: 29.9,
    id: 1,
  },
  {
    imageUrl: 'https://example.com/images/interstellar.jpg',
    releaseDate: '2014-11-07',
    name: 'Interestelar',
    rate: 8.6,
    genres: ['Drama', 'Ficção Científica', 'Aventura'],
    price: 24.9,
    id: 11,
  },
  {
    imageUrl: 'https://example.com/images/parasite.jpg',
    releaseDate: '2019-05-30',
    name: 'Parasita',
    rate: 8.5,
    genres: ['Drama', 'Thriller', 'Comédia'],
    price: 19.9,
    id: 12,
  },
  {
    imageUrl: 'https://example.com/images/dune.jpg',
    releaseDate: '2021-10-22',
    name: 'Duna',
    rate: 8.0,
    genres: ['Ficção Científica', 'Aventura', 'Drama'],
    price: 34.9,
    id: 13,
  },
  {
    imageUrl: 'https://example.com/images/everything-everywhere.jpg',
    releaseDate: '2022-03-25',
    name: 'Tudo em Todo Lugar ao Mesmo Tempo',
    rate: 7.8,
    genres: ['Comédia', 'Drama', 'Ficção Científica'],
    price: 27.9,
    id: 14,
  },
  {
    imageUrl: 'https://example.com/images/top-gun-maverick.jpg',
    releaseDate: '2022-05-27',
    name: 'Top Gun: Maverick',
    rate: 8.3,
    genres: ['Ação', 'Drama'],
    price: 32.9,
    id: 15,
  },
  {
    imageUrl: 'https://example.com/images/avatar-2.jpg',
    releaseDate: '2022-12-16',
    name: 'Avatar: O Caminho da Água',
    rate: 7.6,
    genres: ['Ação', 'Aventura', 'Ficção Científica'],
    price: 39.9,
    id: 16,
  },
  {
    imageUrl: 'https://example.com/images/oppenheimer.jpg',
    releaseDate: '2023-07-21',
    name: 'Oppenheimer',
    rate: 8.4,
    genres: ['Drama', 'História', 'Biografia'],
    price: 31.9,
    id: 17,
  },
]
